# Generated by Django 3.2.8 on 2021-10-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discriminacion',
            name='caso',
        ),
        migrations.AddField(
            model_name='discriminacion',
            name='estado',
            field=models.CharField(choices=[('nol', 'No leido'), ('ong', 'En revisión'), ('fin', 'Finalizado')], default='nol', max_length=255),
        ),
        migrations.AddField(
            model_name='discriminacion',
            name='fecha_creacion',
            field=models.DateField(default='2120-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maltrato',
            name='tipo_maltrato',
            field=models.CharField(choices=[('Estudiantes', (('adulto', 'Adulto a Estudiantes'), ('estudiante', 'Estudiante a Estudiante'))), ('Funcionarios', (('alumno_docente', 'Alumno a Docente o Funcionarios'), ('apoderado', 'Apoderado a Docente o Funcionarios')))], default='estudiante', max_length=255, null=True),
        ),
    ]
