# Generated by Django 3.2.8 on 2021-10-20 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pise', '0002_auto_20211020_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedidasMaltrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicionalidad', models.BooleanField()),
                ('devolucion_casa', models.BooleanField()),
                ('expulsion', models.BooleanField()),
                ('suspension_clases', models.BooleanField()),
                ('descripcion_de_medidas', models.CharField(max_length=255)),
                ('caso', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pise.maltrato', verbose_name='Caso Maltrato')),
            ],
            options={
                'verbose_name': 'medida maltrato',
                'verbose_name_plural': 'medidas maltrato',
                'db_table': 'medidas_maltrato',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MedidasConnotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicionalidad', models.BooleanField()),
                ('devolucion_casa', models.BooleanField()),
                ('expulsion', models.BooleanField()),
                ('suspension_clases', models.BooleanField()),
                ('descripcion_de_medidas', models.CharField(max_length=255)),
                ('caso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pise.connotacionsexual', verbose_name='Caso Connotacion Sexual')),
            ],
            options={
                'verbose_name': 'medida connotacion',
                'verbose_name_plural': 'medidas connotacion',
                'db_table': 'medidas_connotacion',
                'ordering': ['-id'],
            },
        ),
    ]
