# Generated by Django 3.2.8 on 2021-10-23 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pise', '0003_medidasconnotacion_medidasmaltrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivacionOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FaltaConvivencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('nol', 'No leido'), ('enrev', 'En revision'), ('fin', 'Finalizado')], default='nol', max_length=255)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('afectado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pise.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='AccidenteEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('nol', 'No leido'), ('enrev', 'En revision'), ('fin', 'Finalizado')], default='nol', max_length=255)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('malestar_fisico', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_familiar_contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('instruccion_familiar', models.CharField(blank=True, max_length=255, null=True)),
                ('consecuencias_medicas', models.CharField(blank=True, max_length=255, null=True)),
                ('detalle_relato', models.TextField(blank=True, null=True)),
                ('testigo_uno', models.CharField(blank=True, max_length=255, null=True)),
                ('testigo_dos', models.CharField(blank=True, max_length=255, null=True)),
                ('archivo_declaracion_individual', models.FileField(blank=True, null=True, upload_to='declaracion_individual')),
                ('llama_apoderado', models.BooleanField(blank=True, null=True)),
                ('accidentado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pise.matricula')),
            ],
            options={
                'verbose_name': 'caso accidente',
                'verbose_name_plural': 'casos accidentes',
                'db_table': 'caso_accidente',
            },
        ),
    ]
