# Generated by Django 3.2.8 on 2021-10-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pise', '0004_accidenteescolar_derivacionotp_faltaconvivencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='faltaconvivencia',
            name='detalle_relato',
            field=models.TextField(blank=True, null=True),
        ),
    ]
