# Generated by Django 3.2.8 on 2021-10-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pise', '0005_faltaconvivencia_detalle_relato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidenteescolar',
            name='archivo_declaracion_individual',
            field=models.FileField(blank=True, null=True, upload_to='declaracion_individual/'),
        ),
    ]
