# Generated by Django 3.2.8 on 2021-11-04 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pise', '0007_funcionarioestablecimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='VulneracionGarantiasConstitucionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VulneracionDerechosFuncionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('nol', 'No leido'), ('enrev', 'En revision'), ('fin', 'Finalizado')], default='nol', max_length=255)),
                ('tipo_vulneracion', models.CharField(choices=[('inc', 'Incumplimiento de obligaciones laborales'), ('nopr', 'No pago de remuneraciones')], default='inc', max_length=255)),
                ('fecha', models.DateField()),
                ('funcionario_afectado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pise.funcionarioestablecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='DificultadConstitucionConsejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('nol', 'No leido'), ('enrev', 'En revision'), ('fin', 'Finalizado')], default='nol', max_length=255)),
                ('tipo_consejos', models.CharField(choices=[('cc_aa', 'Centro de Alumnos(as)'), ('cc_ppaa', 'Centro de padres y apoderados'), ('consejo', 'Consejo de Curso o Comité de buena convivencia')], default='nol', max_length=255)),
                ('fecha', models.DateField()),
                ('detalle', models.CharField(max_length=255)),
                ('funcionario_afectado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pise.funcionarioestablecimiento')),
            ],
            options={
                'verbose_name': 'Dificultad en consejo',
                'verbose_name_plural': 'Dificultades en consejos',
                'db_table': 'dificultad_consejo',
            },
        ),
    ]
