# Generated by Django 3.2.8 on 2021-11-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pise', '0008_dificultadconstitucionconsejo_vulneracionderechosfuncionarios_vulneraciongarantiasconstitucionales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vulneracionderechosfuncionarios',
            options={'verbose_name': 'Vulneracion de derechos a funcionarios', 'verbose_name_plural': 'Vulneraciones de derechos a funcionarios'},
        ),
        migrations.AddField(
            model_name='vulneracionderechosfuncionarios',
            name='detalle',
            field=models.CharField(default='Detalle', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='vulneracionderechosfuncionarios',
            table='vulneracion_derechos_funcionarios',
        ),
    ]
