# Generated by Django 3.2.9 on 2021-11-14 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pise', '0011_alter_maltrato_tipo_maltrato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionarioestablecimiento',
            old_name='fecha_nacionamiento',
            new_name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='funcionarioestablecimiento',
            name='dv',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionarioestablecimiento',
            name='rut',
            field=models.IntegerField(default=18861407),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maltrato',
            name='funcionario_victima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionario_victima', to='pise.funcionarioestablecimiento'),
        ),
    ]
