# Generated by Django 3.2.9 on 2021-11-14 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pise', '0012_auto_20211113_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'email',
                'verbose_name_plural': 'correos',
                'db_table': 'email',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CorreosEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pise.establecimiento')),
                ('lista_mails', models.ManyToManyField(to='pise.Mail')),
            ],
            options={
                'verbose_name': 'correo establecimiento',
                'verbose_name_plural': 'correos por establecimientos',
                'db_table': 'correos_establecimiento',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo_mensaje', models.TextField()),
                ('envio_correos_establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pise.correosestablecimiento')),
            ],
            options={
                'verbose_name': 'alerta rapida',
                'verbose_name_plural': 'alertas',
                'db_table': 'alerta',
                'ordering': ['-id'],
            },
        ),
    ]
