# Generated by Django 3.2.9 on 2022-08-08 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pise', '0015_remove_matricula_desc_grado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='establecimiento',
            old_name='numero_telefonido',
            new_name='telefono',
        ),
    ]
