# Generated by Django 3.2.9 on 2022-08-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pise', '0016_rename_numero_telefonido_establecimiento_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='reglamento_interno',
            field=models.FileField(blank=True, null=True, upload_to='reglamento/'),
        ),
        migrations.AlterModelTable(
            name='establecimiento',
            table='pise_establecimiento',
        ),
    ]
