# Generated by Django 3.2.9 on 2022-08-08 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pise', '0017_auto_20220808_1921'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='establecimiento',
            table=None,
        ),
    ]
