# Generated by Django 3.2.9 on 2022-08-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pise', '0019_auto_20220809_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='genero',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='codigo_etnia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
