# Generated by Django 3.2.9 on 2022-08-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pise', '0020_auto_20220820_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='celular',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
    ]
