# Generated by Django 3.2.9 on 2022-08-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pise', '0021_auto_20220821_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='celular',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='telefono',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
