# Generated by Django 3.2.9 on 2022-09-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pise', '0022_auto_20220821_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='establecimiento',
            options={'verbose_name': 'establecimiento', 'verbose_name_plural': 'establecimientos'},
        ),
        migrations.AlterField(
            model_name='matricula',
            name='genero',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1, null=True),
        ),
        migrations.AlterModelTable(
            name='establecimiento',
            table='pise_establecimiento',
        ),
    ]
