# Generated by Django 3.2.9 on 2022-09-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pise', '0023_auto_20220909_2008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='establecimiento',
            options={},
        ),
        migrations.AlterField(
            model_name='funcionarioestablecimiento',
            name='rut',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='rut',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterModelTable(
            name='establecimiento',
            table=None,
        ),
    ]
