# Generated by Django 3.2.9 on 2022-09-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pise', '0024_auto_20220915_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accidenteescolar',
            old_name='fecha_ingreso',
            new_name='fecha_accidente',
        ),
        migrations.RenameField(
            model_name='accidenteescolar',
            old_name='instruccion_familiar',
            new_name='lugar_del_accidente',
        ),
        migrations.RenameField(
            model_name='accidenteescolar',
            old_name='malestar_fisico',
            new_name='nombre_apoderado',
        ),
        migrations.RenameField(
            model_name='accidenteescolar',
            old_name='detalle_relato',
            new_name='observaciones',
        ),
        migrations.RenameField(
            model_name='accidenteescolar',
            old_name='nombre_familiar_contacto',
            new_name='persona_que_solicito_el_seguro',
        ),
        migrations.RemoveField(
            model_name='accidenteescolar',
            name='llama_apoderado',
        ),
        migrations.RemoveField(
            model_name='accidenteescolar',
            name='testigo_dos',
        ),
        migrations.RemoveField(
            model_name='accidenteescolar',
            name='testigo_uno',
        ),
        migrations.AddField(
            model_name='accidenteescolar',
            name='medio_contacto_apoderado',
            field=models.CharField(choices=[('llamada', 'Llamada'), ('libreta', 'Libreta'), ('presencial', 'Presencial')], default='nol', max_length=255),
        ),
    ]
