# Generated by Django 3.2.9 on 2022-12-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pise', '0025_auto_20220929_1054'),
    ]

    operations = [
        
    ]
